service: slack-resource-bot

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  environment:
    TOKEN: ${self:custom.secrets.token} # Slack API Token
    HOOK: ${self:custom.secrets.hook} # Slack API endpoint
    CONNECTION_STRING: ${self:custom.secrets.connectionString} # DB Connection String

functions:
  handleResource:
    handler: lib/index.generateResource
    events:
      - schedule: cron(30 20 ? * MON-FRI *) # Run every day at 1:30 PM
